---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nginx
spec:
  gateways:
  - istio-system/gateway
  hosts:
  - "chris.somecompany.com"
  http:
  - route:
      - destination:
          host: nginx.web.svc.cluster.local
          subset: v1
        weight: 70
      - destination:
          host: nginx.web.svc.cluster.local
          subset: v2
        weight: 20
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata: 
  name: nginx
  namespace: web
spec:
  host: nginx.web.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
      outlierDetection:
        baseEjectionTime: 3m
        consecutiveErrors: 1
        interval: 1s
        maxEjectionPercent: 100
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
      outlierDetection:
        baseEjectionTime: 3m
        consecutiveErrors: 1
        interval: 1s
        maxEjectionPercent: 100
