---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:chris530/chris530.github.io.git
    targetRevision: HEAD
    path: charts/istio-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true 
        selfHeal: true
        allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
