---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chris530/chris530.github.io
    targetRevision: HEAD
    path: charts/karpenter
    helm:
      parameters:
      - name: clusterName
        value: chris
      - name: aws.defaultInstanceProfile
        value: KarpenterNodeInstanceProfile
      - name: iamrole
        value: arn:aws:iam::571804045559:role/karpenter-controller-chris
      - name: clusterEndpoint
        value: "https://60EFE21AD7BEF932C07F9050F1E9428A.gr7.us-east-1.eks.amazonaws.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true 
        selfHeal: true
        allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
