---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chris530/chris530.github.io
    targetRevision: HEAD
    path: kustomize/karpenter-config/overlays/chris
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true
        selfHeal: true
