apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl
  name: curl
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
  - command:
    - curl
    -  -- 
    - https://raw.githubusercontent.com/chris530/chris530.github.io/main/kustomize/hooks-test
    image: curlimages/curl
    imagePullPolicy: Always
    name: curl
    resources: {}
